# Generated by Django 2.1.1 on 2018-12-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('attributes', models.TextField(blank=True, max_length=1024)),
                ('content', models.TextField(max_length=100000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.Category')),
            ],
            options={
                'ordering': ('category__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('important_thing_that_happened', models.TextField(blank=True, max_length=256)),
                ('one_sentence_description', models.TextField(max_length=256)),
                ('today_i_learned', models.TextField(blank=True, max_length=256, verbose_name='Today I learned')),
                ('what_I_can_improve', models.TextField(blank=True, max_length=256)),
                ('food_eaten', models.TextField(blank=True, max_length=512)),
                ('tags', models.TextField(blank=True, max_length=256)),
                ('content', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ElementInList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'List elements',
                'ordering': ('list__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('one_sentence_description', models.CharField(max_length=256)),
                ('accomplishments', models.TextField(max_length=2048)),
                ('tags', models.CharField(blank=True, max_length=256)),
                ('content', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('one_sentence_description', models.CharField(max_length=256)),
                ('accomplishments', models.TextField(max_length=2048)),
                ('tags', models.CharField(blank=True, max_length=256)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.AddField(
            model_name='elementinlist',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.List'),
        ),
        migrations.AddField(
            model_name='day',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.Mood'),
        ),
    ]
