# Generated by Django 2.1.1 on 2018-10-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('category__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='elementinlist',
            options={'ordering': ('list__name', 'name'), 'verbose_name_plural': 'List elements'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('-year',)},
        ),
        migrations.AddField(
            model_name='year',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
