# Generated by Django 2.1.1 on 2018-12-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('-date', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('parent__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Currency')),
            ],
            options={
                'ordering': ('-date', 'amount'),
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InnerTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('destination_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('-date', 'source_amount'),
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=64)),
                ('borrower', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('due', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ('-date', 'amount'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Currency')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Currency'),
        ),
        migrations.AddField(
            model_name='innertransfer',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transfer_to', to='budget.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='innertransfer',
            name='destination_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Destination_currency', to='budget.Currency'),
        ),
        migrations.AddField(
            model_name='innertransfer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transfer_from', to='budget.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='innertransfer',
            name='source_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Source_currency', to='budget.Currency'),
        ),
        migrations.AddField(
            model_name='income',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.IncomeSource'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Currency'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Location'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Product'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
    ]
