# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models, migrations

def load_data(apps, schema_editor):
    Location = apps.get_model("budget", "Location")
    Location(name='Wrocław', description='I studied Computer Science here.').save()
    Location(name='Mikołów', description='I was born here.').save()
    Location(name='Legnica', description="Nela's Home City.").save()
    Location(name='Leszno', description='City in the way from Wrocław to Boszkowo.').save()
    Location(name='Boszkowo', description='Vacation place, Nela has a place to stay here.').save()
    Location(name='Katowice', description='Big city near Mikołów.').save()

    Vendor = apps.get_model("budget", "Vendor")
    Vendor(name='Biedronka', description='Grocery Store.').save()
    Vendor(name='Żabka', description='Grocery Store.').save()
    Vendor(name='Lidl', description='Grocery Store.').save()
    Vendor(name='Delikatesy', description='Grocery Store.').save()
    Vendor(name='Tesco', description='Grocery Store.').save()
    Vendor(name='Empik', description='Grocery Store.').save()
    Vendor(name='Netflix', description='Monthly subscription.').save()
    Vendor(name='Allegro', description='Everything you bought there.').save()
    Vendor(name='Person', description='Like regular person you met in reality and bought from.').save()

    PaymentMethod = apps.get_model("budget", "PaymentMethod")
    PaymentMethod(name='mBank', initial_amount=0, initial_amount_date='1996-11-24', description='Bank.').save()
    PaymentMethod(name='Santander Bank', initial_amount=0, initial_amount_date='1996-11-24', description='Bank.').save()
    PaymentMethod(name='Santander Bank Credit Card',initial_amount=0, initial_amount_date='1996-11-24', description='Bank.').save()
    PaymentMethod(name='Alior Bank', initial_amount=0, initial_amount_date='1996-11-24', description='Bank.').save()
    PaymentMethod(name='Bon', initial_amount=0, initial_amount_date='1996-11-24', description='Bank.').save()
    PaymentMethod(name='Cash_PLN', initial_amount=0, initial_amount_date='1996-11-24', description='Like physical money, you know, this ancient method of payments.').save()
    PaymentMethod(name='Cash_EUR', initial_amount=0, initial_amount_date='1996-11-24', description='Like physical money, you know, this ancient method of payments. But foreign ones.').save()

    Currency = apps.get_model("budget", "Currency")
    Currency(name='PLN', to_pln_multiplier=1, description='Polish Złoty.').save()
    Currency(name='EUR', to_pln_multiplier=4.29, description='European currency.').save()
    Currency(name='USD', to_pln_multiplier=3.68, description='US Dollars.').save()

    Category = apps.get_model("budget", "Category")
    Category(name='Healthy Food', parent=None, budget=300, description='Food that is generally good for you and a good choice from nutrition perspective.').save()
    Category(name='Unhealthy Food', parent=None, budget=30, description='Food that is not healthy.').save()
    Category(name='Restaurant Food', parent=None, budget=70, description='Food eaten outside of home, prepared for you to eat instantly.').save()
    Category(name='Entertainment', parent=None, budget=100, description='Everything that entertains you.').save()
    Category(name='Clothing', parent=None, budget=100, description='Things you wear or will wear.').save()
    Category(name='Personal', parent=None, budget=100, description='Things and services bought to take better care of yourself.').save()
    Category(name='Transportation', parent=None, budget=100, description='Public transport and owned vehicle payments.').save()
    Category(name='Education', parent=None, budget=100, description='Everything you buy to learn directly from.').save()
    Category(name='Housing and Utilities', budget=1100, parent=None, description='All payments related to housing and use of media.').save()
    Category(name='Houshold Items/Supplies', budget=100, parent=None, description='Items you buy for the home.').save()
    Category(name='Medical', budget=100, parent=None, description='All payments related to medicaments, medical care and medical devices.').save()
    Category(name='Insurance', budget=20, parent=None, description='Sometimes better buy it.').save()
    Category(name='Gifts', budget=100, parent=None, description='Gifts and donations. If I buy someone food and he does not give me back money for it, it is also a gift.').save()
    # Healthy Food category
    Category(name='Vegetable', parent=Category.objects.get(name='Healthy Food'), description='Vegetable.').save()
    Category(name='Fruit', parent=Category.objects.get(name='Healthy Food'), description='Fruit.').save()
    Category(name='Meat', parent=Category.objects.get(name='Healthy Food'), description='Any, excluding fish, it\'s not meat because meat is flesh of animals on land.').save()
    Category(name='Seafood', parent=Category.objects.get(name='Healthy Food'), description='Everything that lives in the water.').save()
    Category(name='Diary and eggs', parent=Category.objects.get(name='Healthy Food'), description='Milk products and eggs.').save()
    Category(name='Grains, beans and legumes', parent=Category.objects.get(name='Healthy Food'), description='Baked goods, cereal, beans and so on.').save()
    Category(name='Fats and oils', parent=Category.objects.get(name='Healthy Food'), description='Oil or butter.').save()
    Category(name='Spices and herbs', parent=Category.objects.get(name='Healthy Food'), description='Use then wisely. So that food is not bland or too spicy.').save()
    Category(name='Liquid', parent=Category.objects.get(name='Healthy Food'), description='Water, juices, tea.').save()
    # Unhealthy Food category
    Category(name='Drinks', parent=Category.objects.get(name='Unhealthy Food'), description='Cola, juices and so on.').save()
    Category(name='Snacks', parent=Category.objects.get(name='Unhealthy Food'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Chips', parent=Category.objects.get(name='Snacks'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Peanuts', parent=Category.objects.get(name='Snacks'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Confections', parent=Category.objects.get(name='Snacks'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Jellybeans', parent=Category.objects.get(name='Confections'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Chocolate', parent=Category.objects.get(name='Confections'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Candy', parent=Category.objects.get(name='Confections'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Baked', parent=Category.objects.get(name='Confections'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()

    Category(name='Convenience foods', parent=Category.objects.get(name='Unhealthy Food'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Pizza', parent=Category.objects.get(name='Convenience foods'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Pierogi', parent=Category.objects.get(name='Convenience foods'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Pseudo-meat', parent=Category.objects.get(name='Convenience foods'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    Category(name='Lasagne', parent=Category.objects.get(name='Convenience foods'), description='Those pre-packaged, unhealthy ones. Not from restaurant.').save()
    # Restaurant Food category
    Category(name='Bakery/Confecionary', parent=Category.objects.get(name='Restaurant Food'), description='Sweet baked goods.').save()
    Category(name='Fast Food', parent=Category.objects.get(name='Restaurant Food'), description='Burgers, Doners and stuff.').save()
    Category(name='Cafe', parent=Category.objects.get(name='Restaurant Food'), description='Coffee and cookies.').save()
    Category(name='Restaurant', parent=Category.objects.get(name='Restaurant Food'), description='Standard moderetely healthy meal.').save()
    Category(name='Fancy restaurant', parent=Category.objects.get(name='Restaurant Food'), description='Luxury experience.').save()
    # Entertainment category
    Category(name='Alcohol', parent=Category.objects.get(name='Entertainment'), description='Drug.').save()
    Category(name='Parties', parent=Category.objects.get(name='Entertainment'), description='Fun in cleanest essence, with people you like, with people you love.').save()
    Category(name='Games', parent=Category.objects.get(name='Entertainment'), description='Board games, computer games, TTPRPGs.').save()
    Category(name='Movies', parent=Category.objects.get(name='Entertainment'), description='Both in cinema and bought/rented to watch at home.').save()
    Category(name='Concerts', parent=Category.objects.get(name='Entertainment'), description='Some will probably happen.').save()
    Category(name='Vacations', parent=Category.objects.get(name='Entertainment'), description='Yay!').save()
    Category(name='Subscriptions', parent=Category.objects.get(name='Entertainment'), description='Netflix, Amazon, Hulu, etc.').save()
    # Clothing category
    Category(name='Underwear', parent=Category.objects.get(name='Clothing'), description='Socks and underpants.').save()
    Category(name='Sport', parent=Category.objects.get(name='Clothing'), description='Clothes that are used for sport.').save()
    Category(name='Shoes', parent=Category.objects.get(name='Sport'), description='Sport shoes.').save()
    Category(name='Upperbody wear', parent=Category.objects.get(name='Sport'), description='Winter sport coats for skiing, ski underwear and other things.').save()
    Category(name='Lowerbody wear', parent=Category.objects.get(name='Sport'), description='Snowboard pants and so on.').save()
    Category(name='Head wear', parent=Category.objects.get(name='Sport'), description='Helmet, bandanna, ect.').save()

    Category(name='Elegant', parent=Category.objects.get(name='Clothing'), description='Elegant clothes.').save()
    Category(name='Suits', parent=Category.objects.get(name='Elegant'), description='All parts of it.').save()
    Category(name='Shoes', parent=Category.objects.get(name='Elegant'), description='Patant leather shoes.').save()
    Category(name='Pants', parent=Category.objects.get(name='Elegant'), description='Suit pants.').save()
    Category(name='Shirt', parent=Category.objects.get(name='Elegant'), description='Shirts, all of them, even sporty ones.').save()
    Category(name='Tie', parent=Category.objects.get(name='Elegant'), description='Self explanatory, I think.').save()
    Category(name='Outer coat', parent=Category.objects.get(name='Elegant'), description='Coats.').save()

    Category(name='Casual', parent=Category.objects.get(name='Clothing'), description='Casual, everyday clothes.').save()
    Category(name='Shoes', parent=Category.objects.get(name='Casual'), description='Summer to winter shoes, even flipflops or home shoes.').save()
    Category(name='Upperbody wear', parent=Category.objects.get(name='Casual'), description='T-shirts.').save()
    Category(name='Lowerbody wear', parent=Category.objects.get(name='Casual'), description='Pants, short, long, who cares.').save()
    # Personal category
    Category(name='Gym memberships', parent=Category.objects.get(name='Personal'), description='Like you go to the gym frequently, please.').save()
    Category(name='Haircut', parent=Category.objects.get(name='Personal'), description='Like, you go in, you get out, you look worse, but you will look better in a week. Never ending story.').save()
    Category(name='Salon services', parent=Category.objects.get(name='Personal'), description='You have haircut in here, do you really need more?').save()
    Category(name='Equipment', parent=Category.objects.get(name='Personal'), description='Like headphones or a computer!').save()
    Category(name='Cosmetics', parent=Category.objects.get(name='Personal'), description='Be clean, people like when you do not smell sweaty.').save()
    Category(name='Babysitter', parent=Category.objects.get(name='Personal'), description='What? No no no. No children.').save()
    Category(name='Subscriptions', parent=Category.objects.get(name='Personal'), description='We all love it, those burn through our money like slowly, but relentlesly.').save()
    # Transportation category
    Category(name='Public transport', parent=Category.objects.get(name='Transportation'), description='Somethimes you have to take those, have you ever considered only taking those? No? Now look at the cost of other things in this category. Still no?').save()
    Category(name='Vehicle payment', parent=Category.objects.get(name='Transportation'), description='Buy it, rent it, I do not care.').save()
    Category(name='Gas', parent=Category.objects.get(name='Transportation'), description='Like in 50 years this category will be dead..').save()
    Category(name='Tires', parent=Category.objects.get(name='Transportation'), description='Change them yourself and you do not pay for it. Make them yourself and you do not have to include this category.').save()
    Category(name='Maintenance and oil changes', parent=Category.objects.get(name='Transportation'), description='Like, you need to clean it from time to time. Am I right?.').save()
    Category(name='Parking fees', parent=Category.objects.get(name='Transportation'), description='Yea, my favourites.').save()
    Category(name='Repairs', parent=Category.objects.get(name='Transportation'), description='Like you need to repair a car, really? You have a Toyota man, those do not break.').save()
    Category(name='Registration and DMV Fees', parent=Category.objects.get(name='Transportation'), description='Other costs for a car or motorcycle.').save()
    # Education category
    Category(name='Book', parent=Category.objects.get(name='Education'), description='Non-fiction books.').save()
    Category(name='E-learning course', parent=Category.objects.get(name='Education'), description='Stackskills, Udemy and others. ').save()
    Category(name='College', parent=Category.objects.get(name='Education'), description='Generally, if I fail something or pay for my university document or diploma.').save()
    Category(name='School Supplies', parent=Category.objects.get(name='Education'), description='Like notebooks or pens.').save()
    # Housing and Utilities category
    Category(name='Rent', parent=Category.objects.get(name='Housing and Utilities'), description='Make it as small as possible.').save()
    Category(name='Property taxes', parent=Category.objects.get(name='Housing and Utilities'), description='I love them, everybody loves them.').save()
    Category(name='Household repairs', parent=Category.objects.get(name='Housing and Utilities'), description='Hope you won\'t have to spend much on it.').save()
    Category(name='HOA fees', parent=Category.objects.get(name='Housing and Utilities'), description='If you have one of course.').save()
    Category(name='Electricity', parent=Category.objects.get(name='Housing and Utilities'), description='better pay those bills. Lack of it can be huge pain in the ass.').save()
    Category(name='Water', parent=Category.objects.get(name='Housing and Utilities'), description='Most expensive utility? Maybe, if you don\'t heat up the apartment with gas.').save()
    Category(name='Garbage', parent=Category.objects.get(name='Housing and Utilities'), description='Garbage, garbage, good that there are pople who handle this stuff.').save()
    Category(name='Phone', parent=Category.objects.get(name='Housing and Utilities'), description='Like 19 zł per month is an issue for such a service.').save()
    Category(name='Internet', parent=Category.objects.get(name='Housing and Utilities'), description='Necessary stuff, but maybe you won\'t have to pay.').save()
    Category(name='Cable', parent=Category.objects.get(name='Housing and Utilities'), description='You don\'t use it. Just a placeholder category. Probably.').save()
    Category(name='Gas', parent=Category.objects.get(name='Housing and Utilities'), description='M?.').save()
    Category(name='Heating', parent=Category.objects.get(name='Housing and Utilities'), description='Nela says it\'s a necessary category.').save()
    # Houshold Items/Supplies category
    Category(name='Toiletries', parent=Category.objects.get(name='Houshold Items/Supplies'), description='Difficult category. Generally, personal cosmetics, that I buy and everybody uses.').save()
    Category(name='Laundry detergent', parent=Category.objects.get(name='Houshold Items/Supplies'), description='Self explanatory, can as a washing powder, can be laundry pods.').save()
    Category(name='Cleaning supplies', parent=Category.objects.get(name='Houshold Items/Supplies'), description='Cif, Duck, Tymek and others.').save()
    Category(name='Tools', parent=Category.objects.get(name='Houshold Items/Supplies'), description='Like i need names, but stuff you wash house with, including vacum bags.').save()
    # Medical category
    Category(name='Primary care', parent=Category.objects.get(name='Medical'), description='Hope you won\'t have to spend much on this one.').save()
    Category(name='Dental care', parent=Category.objects.get(name='Medical'), description='Those teeth are important, really. Your older self will thank you.').save()
    Category(name='Specialty care', parent=Category.objects.get(name='Medical'), description='Those private specialist (orthodontics, optometrists, etc.), those are the only option this days right?').save()
    Category(name='Urgent care', parent=Category.objects.get(name='Medical'), description='Hope insurence covers it.').save()
    Category(name='Medications', parent=Category.objects.get(name='Medical'), description='Use as little as possible.').save()
    Category(name='Medical devices', parent=Category.objects.get(name='Medical'), description='Sometimes, maybe? Where would you put bathroom scale?').save()
    # Insurance category
    Category(name='Credit/Debit Card insurance', parent=Category.objects.get(name='Insurance'), description='Try to drop them, clever talk.').save()
    Category(name='Travel insurance', parent=Category.objects.get(name='Insurance'), description='Better be save on those skies.').save()
    Category(name='Health insurance', parent=Category.objects.get(name='Insurance'), description='Isn\'t it tax in Poland.').save()
    Category(name="Homeowner's or renter's insurance", parent=Category.objects.get(name='Insurance'), description='Better get it back.').save()
    Category(name='Auto insurance', parent=Category.objects.get(name='Insurance'), description='Another downside to owning a car.').save()
    Category(name='Life insurance', parent=Category.objects.get(name='Insurance'), description='Wow, this gives perspective.').save()
    Category(name='Disability insurance', parent=Category.objects.get(name='Insurance'), description='Isn\'t it the travel one?').save()
    # Gifts category
    Category(name='Birthday', parent=Category.objects.get(name='Gifts'), description='Yea, thay have those every year.').save()
    Category(name='Dating', parent=Category.objects.get(name='Gifts'), description='This category is slippery, I don\'t really want to keep track of that, but budget is budget.').save()
    Category(name='Anniversary', parent=Category.objects.get(name='Gifts'), description='We have plenty of those.').save()
    Category(name='Wedding', parent=Category.objects.get(name='Gifts'), description='There will be some.').save()
    Category(name='Christmas', parent=Category.objects.get(name='Gifts'), description='Yay! All those presents. Let\'s buy them ealier.').save()
    Category(name='Special occasion', parent=Category.objects.get(name='Gifts'), description='There is someone for who special occasion is everyday.').save()
    Category(name='Charities', parent=Category.objects.get(name='Gifts'), description='You know, there is always this 1%.').save()

    IncomeSource = apps.get_model("budget", "IncomeSource")
    IncomeSource(name="Job", description='Work hard! Have fun! Be nice! Earn big!').save()
    IncomeSource(name='Parents', description='When I am young, they help with that.').save()
    IncomeSource(name="Found", description='It was right there, just laying. And now it\'s mine.').save()
    IncomeSource(name="Stolen", description='I am not telling I want to put something here.').save()
    IncomeSource(name="Gifts", description='Thank you very much!').save()
    IncomeSource(name="Side-hustle", description='Hobby can earn some money, right?').save()
    IncomeSource(name="Money-back", description='Yea, some discounts work like that.').save()
    IncomeSource(name="Investments", description='Hope those go well.').save()


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(load_data),
    ]
