# Generated by Django 2.1.1 on 2018-10-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_init_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent__parent__name', 'parent__name', 'name'), 'verbose_name_plural': 'Categories'},
        ),
    ]
