# Generated by Django 2.1.1 on 2018-10-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20181016_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boughtproduct',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent__parent__parent__name', 'parent__parent__name', 'parent__name', 'name'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
