# Generated by Django 2.1.1 on 2018-11-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20181017_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent__name', 'name'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
    ]
