# Generated by Django 2.1.1 on 2018-10-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={'ordering': ('-date', 'category__name')},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('-done', 'category__name', 'name')},
        ),
    ]
