# Generated by Django 2.1.1 on 2018-12-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cooking_time', models.DurationField()),
                ('estimated_price_pln', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredients', models.TextField(max_length=2000)),
                ('cooking_instructions', models.TextField(max_length=10000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
