# Generated by Django 2.1.1 on 2018-10-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNutritionValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Energy (cal)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('fibre', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('salt', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.Product')),
            ],
            options={
                'verbose_name_plural': 'Product nutrition values',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', models.TextField(max_length=10000)),
                ('cooking_instructions', models.TextField(max_length=10000)),
            ],
        ),
    ]
